name: Create Executable

on:
  push:
    branches:
      - main
      - add-pyinstaller-ci

jobs:
  createExecutable:
    name: Create Executable
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # cache pip dependencies
      - run: pip install -r python/requirements.txt
      - run: pip install pyinstaller
      

      
