name: Run tests

on:
  push:

jobs:
  UnitTest:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' # cache pip dependencies
      
      - name: Install required dependencies
        run: pip install -r python/requirements.txt
      
      - name: Run Unit Tests
        run: python -m unittest discover -s ./python/src